baseURL = "https://www.wiktordyngosz.pl"
languageCode = "en-us"
title = "Wiktor Dyngosz"
theme = "vanilla-bootstrap-hugo-theme"
googleAnalytics = "UA-134763748-1"

# Google SEO
enableRobotsTXT = true
canonifyURLs = true

# Uncomment below to enable syntax highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    pre = "edit"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  includeBootstrapJs = false
  showActiveNav = true
  dateFormat = "Jan 2, 2006"
  footerText = "Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
  hideFooter = false

[params.contact]
    email = "wiktor.dyngosz@gmail.com"
    twitter = "WiktorDyngosz"
    linkedin = "https://www.linkedin.com/in/wiktordyngosz/"
    github = "dyngosz"

[params.about]
    enable = true
    subtitle = "Hi, I'm Wiktor"
    subtitle2 = "CEO and Founder at Peakforce"
    subtitle3 = "Based in Poland 🇵🇱"
    aboutMe = ["**Currently leading [Peakforce](https://www.peakforce.dev/) where I help companies get the most out of Atlassian and Splunk platforms.**",
    "Over a decade in the IT world taught me that learning never stops and teamwork is everything. I like to keep things simple, practical and human.",
    "Working (mostly) remotely since 2018. In my spare I am usually either riding/bikepacking on my gravel bike or hiking in the mountains. ",
    "I <i class=heart-icon data-feather=heart></i> all board sports: snowboard, surfing, wake, kite (still <i>ToDo</i>) and [splitboard](https://www.nonstopsnow.com/journal/what-is-splitboarding).",
    "Tennis is my newly rediscovered hobby (after a 15 year break).",
    "I used to write [a bit](/post/). Nowadays I do it mostly on [LinkedIn](https://www.linkedin.com/in/wiktordyngosz/)."]
